#ifndef M_NAME_TABLE_H
#define M_NAME_TABLE_H

/*
 * Item-name constants used by the JoyBoot payload.  The names and values are
 * shared with ac-decomp's m_name_table.h.  The 0xFEA1-0xFEB2 entries are the
 * Animal Island random-item placeholders; ac-decomp currently uses their raw
 * values in m_shop.c, so they are named here for the role that code assigns.
 */

enum {
    NAME_TYPE_ITEM0,
    NAME_TYPE_FTR0,
    NAME_TYPE_ITEM1,
    NAME_TYPE_FTR1,
};

enum {
    ITEM1_CAT_PAPER,
    ITEM1_CAT_MONEY,
    ITEM1_CAT_TOOL,
    ITEM1_CAT_FISH,
    ITEM1_CAT_CLOTH,
    ITEM1_CAT_ETC,
    ITEM1_CAT_CARPET,
    ITEM1_CAT_WALL,
    ITEM1_CAT_FRUIT,
    ITEM1_CAT_PLANT,
    ITEM1_CAT_MINIDISK,
    ITEM1_CAT_DUMMY,
    ITEM1_CAT_TICKET,
    ITEM1_CAT_INSECT,
    ITEM1_CAT_HUKUBUKURO,
    ITEM1_CAT_KABU,
};

#define ITEM_NAME_MASK_TYPE(item) ((item) & 0xF000)
#define ITEM_NAME_MASK_CAT(item) ((item) & 0x0F00)

#define ITEM_NAME_CHK_TYPE(item, type) (ITEM_NAME_MASK_TYPE(item) == ((type) << 12))

#define ITEM_NAME_GET_TYPE(item) (ITEM_NAME_MASK_TYPE(item) >> 12)
#define ITEM_NAME_GET_CAT(item)  (((item) >> 8) & 0xF)

#define ITEM_IS_FTR(n) \
  (ITEM_NAME_MASK_TYPE(n) == (NAME_TYPE_FTR0 << 12) || ITEM_NAME_MASK_TYPE(n) == (NAME_TYPE_FTR1 << 12))

#define EMPTY_NO 0x0000

#define TREE_STUMP001 (EMPTY_NO + 1)
#define TREE_STUMP002 (EMPTY_NO + 2)
#define TREE_STUMP003 (EMPTY_NO + 3)
#define TREE_STUMP004 (EMPTY_NO + 4)

#define GRASS_A 0x0008
#define GRASS_C 0x000A

#define HOLE_START 0x0011
#define HOLE_END 0x0029
#define BURIED_PITFALL_HOLE_START 0x002A
#define BURIED_PITFALL_HOLE_END 0x0042
#define BURIED_PITFALL_HOLE_RSV_END 0x005B

#define TREE_BEES 0x005E
#define TREE_FTR 0x005F
#define ROCK_A 0x0063
#define ROCK_E 0x0067
#define TREE_BELLS 0x0069
#define MONEY_ROCK_A 0x006A
#define MONEY_ROCK_E 0x006E

#define TREE_PALM_STUMP001 0x0070
#define TREE_PALM_STUMP002 0x0071
#define TREE_PALM_STUMP003 0x0072
#define TREE_PALM_STUMP004 0x0073

#define ENV_START 0x0800
#define TREE_SAPLING (ENV_START + 0)
#define TREE_S0 (ENV_START + 1)
#define TREE_S1 (ENV_START + 2)
#define TREE_S2 (ENV_START + 3)
#define TREE (ENV_START + 4)

#define TREE_APPLE_SAPLING (ENV_START + 5)
#define TREE_APPLE_S0 (ENV_START + 6)
#define TREE_APPLE_S1 (ENV_START + 7)
#define TREE_APPLE_S2 (ENV_START + 8)
#define TREE_APPLE_NOFRUIT_0 (ENV_START + 9)
#define TREE_APPLE_NOFRUIT_2 (ENV_START + 11)
#define TREE_APPLE_FRUIT (ENV_START + 12)

#define TREE_ORANGE_SAPLING (ENV_START + 13)
#define TREE_ORANGE_S0 (ENV_START + 14)
#define TREE_ORANGE_S1 (ENV_START + 15)
#define TREE_ORANGE_S2 (ENV_START + 16)
#define TREE_ORANGE_NOFRUIT_0 (ENV_START + 17)
#define TREE_ORANGE_NOFRUIT_2 (ENV_START + 19)
#define TREE_ORANGE_FRUIT (ENV_START + 20)

#define TREE_PEACH_SAPLING (ENV_START + 21)
#define TREE_PEACH_S0 (ENV_START + 22)
#define TREE_PEACH_S1 (ENV_START + 23)
#define TREE_PEACH_S2 (ENV_START + 24)
#define TREE_PEACH_NOFRUIT_0 (ENV_START + 25)
#define TREE_PEACH_NOFRUIT_2 (ENV_START + 27)
#define TREE_PEACH_FRUIT (ENV_START + 28)

#define TREE_PEAR_SAPLING (ENV_START + 29)
#define TREE_PEAR_S0 (ENV_START + 30)
#define TREE_PEAR_S1 (ENV_START + 31)
#define TREE_PEAR_S2 (ENV_START + 32)
#define TREE_PEAR_NOFRUIT_0 (ENV_START + 33)
#define TREE_PEAR_NOFRUIT_2 (ENV_START + 35)
#define TREE_PEAR_FRUIT (ENV_START + 36)

#define TREE_CHERRY_SAPLING (ENV_START + 37)
#define TREE_CHERRY_S0 (ENV_START + 38)
#define TREE_CHERRY_S1 (ENV_START + 39)
#define TREE_CHERRY_S2 (ENV_START + 40)
#define TREE_CHERRY_NOFRUIT_0 (ENV_START + 41)
#define TREE_CHERRY_NOFRUIT_2 (ENV_START + 43)
#define TREE_CHERRY_FRUIT (ENV_START + 44)

#define TREE_1000BELLS_SAPLING (ENV_START + 45)
#define TREE_1000BELLS_S0 (ENV_START + 46)
#define TREE_1000BELLS_S1 (ENV_START + 47)
#define TREE_1000BELLS_S2 (ENV_START + 48)
#define TREE_1000BELLS (ENV_START + 49)
#define TREE_10000BELLS_SAPLING (ENV_START + 50)
#define TREE_10000BELLS_S0 (ENV_START + 51)
#define TREE_10000BELLS_S1 (ENV_START + 52)
#define TREE_10000BELLS_S2 (ENV_START + 53)
#define TREE_10000BELLS (ENV_START + 54)
#define TREE_30000BELLS_SAPLING (ENV_START + 55)
#define TREE_30000BELLS_S0 (ENV_START + 56)
#define TREE_30000BELLS_S1 (ENV_START + 57)
#define TREE_30000BELLS_S2 (ENV_START + 58)
#define TREE_30000BELLS (ENV_START + 59)

#define FLOWER_LEAVES_PANSIES0 (ENV_START + 60)
#define FLOWER_LEAVES_TULIP2 (ENV_START + 68)
#define FLOWER_PANSIES0 (ENV_START + 69)
#define FLOWER_PANSIES1 (ENV_START + 70)
#define FLOWER_PANSIES2 (ENV_START + 71)
#define FLOWER_COSMOS0 (ENV_START + 72)
#define FLOWER_COSMOS1 (ENV_START + 73)
#define FLOWER_COSMOS2 (ENV_START + 74)
#define FLOWER_TULIP0 (ENV_START + 75)
#define FLOWER_TULIP1 (ENV_START + 76)
#define FLOWER_TULIP2 (ENV_START + 77)
#define DEAD_SAPLING (ENV_START + 78)

#define TREE_100BELLS_SAPLING (ENV_START + 79)
#define TREE_100BELLS_S0 (ENV_START + 80)
#define TREE_100BELLS_S1 (ENV_START + 81)
#define TREE_100BELLS_S2 (ENV_START + 82)
#define TREE_100BELLS (ENV_START + 83)

#define TREE_PALM_SAPLING (ENV_START + 84)
#define TREE_PALM_S0 (ENV_START + 85)
#define TREE_PALM_S1 (ENV_START + 86)
#define TREE_PALM_S2 (ENV_START + 87)
#define TREE_PALM_NOFRUIT_0 (ENV_START + 88)
#define TREE_PALM_NOFRUIT_2 (ENV_START + 90)
#define TREE_PALM_FRUIT (ENV_START + 91)
#define DEAD_PALM_SAPLING (ENV_START + 92)
#define CEDAR_TREE_SAPLING (ENV_START + 93)
#define DEAD_CEDAR_SAPLING (ENV_START + 98)

/* Furniture ranges after applying FTR_START/FTR_END. */
#define HANIWA_START 0x15B0
#define HANIWA_END 0x17AB
#define FTR_FAMICOM_START 0x1DA8
#define FTR_FAMICOM_END 0x1DF7
#define FTR_DINO_START 0x1EEC
#define FTR_DINO_END 0x1F4F

#define ITM_MONEY_1000 0x2100
#define ITM_MONEY_10000 0x2101
#define ITM_MONEY_30000 0x2102
#define ITM_MONEY_100 0x2103

#define ITM_NET 0x2200
#define ITM_AXE 0x2201
#define ITM_SHOVEL 0x2202
#define ITM_ROD 0x2203
#define ITM_UMBRELLA_START 0x2204
#define ITM_UMBRELLA31 0x2223
#define ITM_RED_PAINT 0x222D
#define ITM_BROWN_PAINT 0x2238
#define ITM_GOLDEN_NET 0x2239
#define ITM_GOLDEN_AXE 0x223A
#define ITM_GOLDEN_SHOVEL 0x223B
#define ITM_GOLDEN_ROD 0x223C
#define ITM_AXE_USE_1 0x223D
#define ITM_AXE_USE_2 0x223E
#define ITM_AXE_USE_3 0x223F
#define ITM_AXE_USE_4 0x2240
#define ITM_AXE_USE_5 0x2241
#define ITM_AXE_USE_6 0x2242
#define ITM_AXE_USE_7 0x2243
#define ITM_BALLOON_START 0x2244
#define ITM_BUNNY_O_BALLOON 0x224B
#define ITM_YELLOW_PINWHEEL 0x224C
#define ITM_FANCY_PINWHEEL 0x2253
#define ITM_BLUEBELL_FAN 0x2254
#define ITM_LEAF_FAN 0x225B

#define ITM_DUST0_EMPTY_CAN 0x250E
#define ITM_DUST2_OLD_TIRE 0x2510
#define ITM_FOSSIL 0x2511
#define ITM_PITFALL 0x2512
#define ITM_SHELL0 0x2514
#define ITM_SHELL1 0x2515
#define ITM_SHELL2 0x2516
#define ITM_SHELL3 0x2517
#define ITM_SHELL4 0x2518
#define ITM_SHELL5 0x2519
#define ITM_SHELL6 0x251A
#define ITM_SHELL7 0x251B
#define ITM_SIGNBOARD 0x251E

#define ITM_FOOD_APPLE 0x2800
#define ITM_FOOD_CHERRY 0x2801
#define ITM_FOOD_PEAR 0x2802
#define ITM_FOOD_PEACH 0x2803
#define ITM_FOOD_ORANGE 0x2804
#define ITM_FOOD_MUSHROOM 0x2805
#define ITM_FOOD_CANDY 0x2806
#define ITM_FOOD_COCONUT 0x2807

#define ITM_WHITE_PANSY_BAG 0x2902
#define ITM_YELLOW_TULIP_BAG 0x290A

#define STRUCTURE_START 0x5800
#define FLAG (STRUCTURE_START + 78)
#define COTTAGE_MY (STRUCTURE_START + 80)
#define COTTAGE_NPC (STRUCTURE_START + 81)

#define RSV_ISLAND_FTR_COMMON 0xFEA1
#define RSV_ISLAND_FTR_RARE 0xFEA2
#define RSV_ISLAND_FTR_EVENT 0xFEA3
#define RSV_ISLAND_FAMICOM 0xFEA4
#define RSV_ISLAND_FTR_ISLAND 0xFEA5
#define RSV_ISLAND_FOSSIL 0xFEA6
#define RSV_ISLAND_MINIDISK 0xFEA7
#define RSV_ISLAND_HANIWA 0xFEA8
#define RSV_ISLAND_UMBRELLA 0xFEA9
#define RSV_ISLAND_CARPET_COMMON 0xFEAA
#define RSV_ISLAND_CARPET_RARE 0xFEAB
#define RSV_ISLAND_WALL_COMMON 0xFEAC
#define RSV_ISLAND_WALL_RARE 0xFEAD
#define RSV_ISLAND_CLOTH_COMMON 0xFEAE
#define RSV_ISLAND_CLOTH_RARE 0xFEAF
#define RSV_ISLAND_HOLE 0xFEB0
#define RSV_ISLAND_FLOWER_BAG 0xFEB1
#define RSV_ISLAND_TRASH 0xFEB2
#define RSV_NO 0xFFFF

#endif
